### ISSUE TITLE
JavaScript error: `Uncaught Error: entity n3275503 not found`

### ISSUE THREAD

**Issue by nateirwin** [nationalparkservice/places-editor#77]

**Comment by jimmyrocks** [comment]
This looks like a conflict where the node was deleted in version 2 (at 2:20
by nate using iD), but added back to the object in version 3 (at 4:10 by
Jake using JOSM).

I am guessing that Jake had downloaded this into JOSM before nate made a
change, and re-uploaded it including a node that Nate deleted.

I will need to research how the OpenStreetMap server deals with their edge
case in order to solve the problem entirely. But I can fix this node
quickly.

**Comment by nateirwin** [comment]
I suspected it was something like that. Sounds like we probably don't need to spend too much time looking into the issue, just wanted to make sure the node was fixed. Thanks!
