### ISSUE TITLE
Forts - places of interest or building

### ISSUE THREAD

**Issue by RangerLaura** [nationalparkservice/places-editor#86]
I am putting together an NPMap of Forts in the NPS and was hoping to pull in existing buildings that are forts and add new ones in a consistent manner.  There are many fortifications already in park tiles, but they are marked as building footprints not as 'Forts' or Fortifications.  Across the NPS, some forts are earthen and some are buildings.

My question was to look at whether or not Forts could be a supported polygon type in Places? Or if there was a standardized way that people could should address Fortifications across NPS sites (there are also batteries and gun emplacements).  Thank you,
Laura

**Comment by nateirwin** [comment]
Hi @RangerLaura,

I think this something we may want to support in the future. Currently, most fortifications in our system came in as buildings from the NPS' servicewide buildings GIS dataset. I believe they are in this dataset because FMSS classifies them as structures. Cc'ing @bdiethorn in case he has feedback on this issue.

**Comment by bdiethorn** [comment]
In FMSS Fortification have an asset code of 7300 and buildings are 4100.
In the Enterprise buildings database we left it up to the individual parks
to make a decision on if they wanted to include forts in the buildings
layer or not.  Most parks chose to include them. Personally I always
thought it better to consider the buildings layer as an enterprise
structures layer because in most cases forts and some large kiosks have
been included.  Because of this places should have a lot of fortifications
already in the database.

On Wed, Sep 9, 2015 at 3:33 PM, Nate Irwin <notifications@github.com> wrote:

> Hi @RangerLaura <https://github.com/RangerLaura>,
>
> I think this something we may want to support in the future. Currently,
> most fortifications in our system came in as buildings from the NPS'
> servicewide buildings GIS dataset. I believe they are in this dataset
> because FMSS classifies them as structures. Cc'ing @bdiethorn
> <https://github.com/bdiethorn> in case he has feedback on this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nationalparkservice/places-editor/issues/86#issuecomment-139052172>
> .
>



-- 
Brian Diethorn - Research Associate
Facilities Management GIS Data Manager
Park Facilities Management Division &
Resource Information Services Division
National Park Service

Phone: 303.987.6976
Fax: 303.987.7636

**Comment by RangerLaura** [comment]
Thanks guys. That is very helpful.  I def agree that places already has a lot of fortification in them. I guess the question is, since most of them are marked as buildings, is there any way for me to find all the fortifications in places to pull into one 'Forts in the NPS' map? Or is it that, since they're just marked as buildings, i'll have to know each park that has a fort and find them one by one?

**Comment by bdiethorn** [comment]
You are welcome.  One way that we could classify these fortifications is to
associate the FMSS ID (location ID) to each structure and utilize the asset
codes to split out what the NPS considers a fortification vs. a building.
In addition I believe that tags can be created in Places if a fort tag does
not exist already.  A report can be run from the Asset Management Reporting
System that can show all of the fortifications that exist in the NPS.

On Tue, Sep 15, 2015 at 7:39 AM, Laura Cohen <notifications@github.com>
wrote:

> Thanks guys. That is very helpful. I def agree that places already has a
> lot of fortification in them. I guess the question is, since most of them
> are marked as buildings, is there any way for me to find all the
> fortifications in places to pull into one 'Forts in the NPS' map? Or is it
> that, since they're just marked as buildings, i'll have to know each park
> that has a fort and find them one by one?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nationalparkservice/places-editor/issues/86#issuecomment-140396020>
> .
>



-- 
Brian Diethorn - Research Associate
Facilities Management GIS Data Manager
Park Facilities Management Division &
Resource Information Services Division
National Park Service

Phone: 303.987.6976
Fax: 303.987.7636

**Comment by nateirwin** [comment]
Hi @RangerLaura: We have now added fortifications as a polygon type in Places Editor. Not sure if this resolves your problem, but wanted to let you know it is out there. We're still working on the data creation/upload functionality in Builder. Closing this for now.
