### ISSUE TITLE
Kansas Parks Map

### ISSUE THREAD

**Issue by avawser** [nationalparkservice/places-editor#89]
Shouldn't Brown vs. Board of Education show up on this map? It is the first park listed for Kansas but is not labeled on the map
![brvb](https://cloud.githubusercontent.com/assets/13888971/9907936/0b01a392-5c57-11e5-8764-eb76567935a4.jpg)

**Comment by jimmyrocks** [comment]
We currently have this label set to display at zoom level 10

This was set on April 30, 2014:
https://github.com/nationalparkservice/mapbox-studio-projects/commit/e802ff3792f57762c7c14f7dcf614814e4890ebb#diff-0979e238764a6754a633f7a4bad43916R97

I don't see any issue that explains why it was set. Although, I'm guessing
the label was conflicting with the label for Topeka.

Without the change, the park would have displayed at zoom level 9
https://github.com/nationalparkservice/mapbox-studio-projects/blob/1b38b6b8eff82f8a21fd3f7d8dc94a0931f8c2f7/park_tiles/park_tiles_data_process/nps_data_compilation/scripts/cleanup/label_point_calc_create.sql#L19-L39

This is because the minzoompoly for the park is 14, but the visitor count
is 26,000.

We can bump it back up to zoom level 9 and experiment with moving the label
to the southwest. This may eliminate some of the clipping issues.

**Comment by nateirwin** [comment]
@jakecoolidge: Is this something you can look at? Seems similar to the Cumberland Gap issue you fixed yesterday.

Thanks for letting us know about the issue, @avawser!

**Comment by jakecoolidge** [comment]
Yeah, thought of taking a look at this, and will do so. I'll run questions by @jimmyrocks as necessary.

**Comment by jakecoolidge** [comment]
In order for BVBR's label to display on the Kansas state page map, it will need to appear at zoom 7. @jimmyrocks and I are going to test this Monday; by then a new test tilesource will be ready and I'll be back in the office.

**Comment by jakecoolidge** [comment]
Test looks great; we'll roll the changes into the main dataset in the next day or so.

**Comment by jakecoolidge** [comment]
Opened the Kansas state page today and BRVB appears right away. Thanks @jimmyrocks!

**Comment by avawser** [comment]
looks good thanks for fixing

Anne Vawser
Archeologist
Archeological Information Management Team Leader
Midwest Archeological Center
National Park Service
100 Centennial Mall North, Room 474
Lincoln, NE 68508

402-437-5392 x 109
402-437-5098 (Fax)
anne_vawser@nps.gov


*Find your Park and Find your Heritage!*
